const rawCommandStore = [
    'open $url',
    'open $url in new window',
    'go $direction',
    'go forward',
    'go back',
    'type $typeText',
    'refresh',
    'accept alert',
    'dismiss alert',
    'drag $source to $destination',
    'drag $source to $destination $destinationIndex',
    'drag $source to $destination near $destinationMarker',
    'drag $source $sourceIndex to $destination',
    'drag $source $sourceIndex to $destination $destinationIndex',
    'drag $source $sourceIndex to $destination near $destinationMarker',
    'drag $source near $sourceMarker to $destination',
    'drag $source near $sourceMarker to $destination $destinationIndex',
    'drag $source near $sourceMarker to $destination near $destinationMarker',
    'read $searchText',
    'read $searchText from url',
    'read $searchText from alert',
    'read $searchText from $identifier',
    'read $searchText $index',
    'read $searchText near $marker',
    'read $searchText from page title',
    'read $searchText to the $direction of $marker',
    'read $searchText from row $row column $column',
    'read $searchText from row $row near $rowMarker column $column near $columnMarker',
    'read $searchText from row $row near $rowMarker column $column',
    'read $searchText from row $row column $column near $columnMarker',
    'read value from $selector field as $destinationVar',
    'read value from $selector field near $marker as $destinationVar',
    'read value from $selector field $elementIndex as $destinationVar',
    'read $selector state as $destinationVar',
    'read $selector state near $marker as $destinationVar',
    'read $selector state $elementIndex as $destinationVar',
    'read active field as $destinationVar',
    'read placeholder from $selector field as $destinationVar',
    'read placeholder from $selector $elementIndex field as $destinationVar',
    'read placeholder from $selector near $marker field as $destinationVar',
    'print $variable',
    'press $inputKeys',
    'clear $what',
    'clear text',
    'clear input',
    'clear highlights',
    'close window',
    'close tab',
    'close $what',
    'highlight $selector',
    'highlight $selector $elementIndex',
    'highlight $selector near $marker',
    'highlight $selector $elementIndex near $marker',
    'check if $selector contains $expectedVal',
    'check if $selector near $marker contains $expectedVal',
    'check if $selector $elementIndex contains $expectedVal',
    'check if $selector is checked',
    'check if $selector near $marker is checked',
    'check if $selector $elementIndex is checked',
    'check if $selector is not checked',
    'check if $selector near $marker is not checked',
    'check if $selector $elementIndex is not checked',
    'check if $selector is enabled',
    'check if $selector $elementIndex is enabled',
    'check if $selector near $marker is enabled',
    'check if $selector is disabled',
    'check if $selector $elementIndex is disabled',
    'check if $selector near $marker is disabled',
    'check if $selector is focused',
    'check if $selector near $marker is focused',
    'check if $selector $elementIndex is focused',
    'check if $selector is not focused',
    'check if $selector near $marker is not focused',
    'check if $selector $elementIndex is not focused',
    'check if $selector is available',
    'check if $selector is not available',
    'check if $actualVal is $expectedVal',
    'check if $actualVal is not $notExpectedVal',
    'copy $sourceVar to $destinationVar',
    'set $storeVar to $value',
    'inspect',
    'switch $what',
    'switch tab',
    'switch window',
    'click $selector',
    'click $selector $elementIndex',
    'click $selector near $marker',
    'click $selector $elementIndex near $marker',
    'click on row $row column $column',
    'click on row $row near $rowMarker column $column near $columnMarker',
    'click on row $row near $rowMarker column $column near $columnMarker $elementIndex',
    'click on row $row near $rowMarker column $column',
    'click on row $row near $rowMarker column $column $elementIndex',
    'click on row $row column $column near $columnMarker',
    'click on row $row column $column near $columnMarker $elementIndex',
    'click on row $row column $column $elementIndex',
    'double click $selector',
    'double click $selector $elementIndex',
    'double click $selector near $marker',
    'double click $selector $elementIndex near $marker',
    'hover $selector',
    'hover $selector $elementIndex',
    'hover $selector near $marker',
    'hover $selector $elementIndex near $marker',
    'hover on row $row column $column',
    'hover on row $row column $column $elementIndex',
    'right click $selector',
    'right click $selector $elementIndex',
    'right click $selector near $marker',
    'right click $selector $elementIndex near $marker',
    'middle click $selector',
    'middle click $selector $elementIndex',
    'middle click $selector near $marker',
    'middle click $selector $elementIndex near $marker',
    'wait $time seconds',
    'wait $time seconds for $selector',
    'wait $time seconds for $selector near $marker',
    'http $method $url as $varName',
    'evaluate $expression as $varName',
    'save browser state as $snapshotReference',
    'load browser state $snapshotReference',
    'execute browser function $functionIdentifier',
    'execute browser function $functionIdentifier with $var1',
    'execute browser function $functionIdentifier with $var1 $var2',
    'execute browser function $functionIdentifier with $var1 $var2 $var3',
    'execute browser function $functionIdentifier with string $argumentString',
    'read $searchText from row $row column $column $index',
    'read $searchText from row $row near $rowMarker column $column near $columnMarker $index',
    'read $searchText from row $row near $rowMarker column $column $index',
    'read $searchText from row $row column $column near $columnMarker $index',
    'lookup $column for $row as $searchText',
    'lookup $column for $row as $searchText $index',
    'lookup $column near $columnMarker for $row near $rowMarker as $searchText $index',
    'lookup $column for $row near $rowMarker as $searchText $index',
    'lookup $column near $columnMarker for $row as $searchText $index',
    'lookup $column near $columnMarker for $row near $rowMarker as $searchText',
    'lookup $column for $row near $rowMarker as $searchText',
    'lookup $column near $columnMarker for $row as $searchText'
]

module.exports = { rawCommandStore };